[tool.ruff]
line-length = 79  # Default PEP8 line length
preview = true  # Enable preview features for additional checks

[tool.ruff.lint]
select = [
    "E",  # All errors related to PEP8
    "W",  # All warnings related to PEP8
    "F",  # All errors related to code quality
    "UP",  # All upgrades related to improving code compatibility and modern syntax
    "B",  # All bugbear-related checks
    "SIM",  # All simplification-related checks
    "I",  # All import sorting-related checks
    "C90",  # Complexity checks related to code readability and maintainability
]

ignore = [] 
